name: Build and Release

permissions:
  contents: write


on:
  push:
    tags:
      - 'v*.*.*' # run on any tag push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Inject tag into module.json
        run: |
          sed -i 's/CI_COMMIT_TAG/${GITHUB_REF_NAME}/g' dist/module.json

      - name: Prepare package
        run: |
          mv dist fvtt-ready-check
          cp fvtt-ready-check/module.json ./
          zip -q fvtt-ready-check.zip -r fvtt-ready-check/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fvtt-ready-check-artifacts
          path: |
            fvtt-ready-check.zip
            module.json

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: fvtt-ready-check-artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: Created using GitHub Actions
          draft: false
          prerelease: false

      - name: Upload fvtt-ready-check.zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fvtt-ready-check.zip
          asset_name: fvtt-ready-check.zip
          asset_content_type: application/zip

      - name: Upload module.json to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module.json
          asset_name: module.json
          asset_content_type: application/json
